<?php

declare(strict_types=1);

namespace Atlasflow\OrderBridge\Support;

/**
 * Utility for generating and tracking transfer_id values.
 *
 * Persistence across sessions (e.g. storing used IDs in a database) is the
 * host application's responsibility. This class tracks IDs in-memory only,
 * which is sufficient for detecting intra-session retries.
 */
final class TransferIdManager
{
    /** @var array<string, true> */
    private array $used = [];

    /**
     * Generate a new UUID v4 and record it as used.
     *
     * Idempotency rules (§5.4):
     * - Generate a new UUID only when the payload content has genuinely changed.
     * - On an identical retry (same payload, transient failure), reuse the existing ID.
     * - The host application is responsible for persisting the UUID so it can be
     *   reused on retry across process restarts.
     */
    public function generate(): string
    {
        $uuid = sprintf(
            '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0x0fff) | 0x4000,
            mt_rand(0, 0x3fff) | 0x8000,
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
        );

        $this->used[$uuid] = true;

        return $uuid;
    }

    /**
     * Return true if the given transfer_id was generated by this instance.
     *
     * A return value of true indicates this is a known retry within the current
     * session. The host application should additionally check its persistent
     * store for cross-session deduplication.
     */
    public function isRetry(string $transferId): bool
    {
        return isset($this->used[$transferId]);
    }
}
